kamuno_analytics:
  target: dev
  outputs:
    dev:
      type: bigquery
      project: mylifedesign
      schema: staging
      method: oauth
      threads: 4
      location: us-central1
      timeout_seconds: 300
      priority: interactive
      retries: 1
